# nginx运行的用户及用户组
user  nginx;
# worker进程数量要与CPU的核数相等
worker_processes  auto;

pid        /var/run/nginx.pid;
error_log  /var/log/nginx/nginx.error.log warn;

# 单个nginx进程打开的最多的文件描述符数目：最好与ulimit -n 的值保持一致
worker_rlimit_nofile 1024;

events {
    # epoll事件处理模型
    use epoll;
    # 单个工作进程可以允许同时建立外部连接的数量：受限于操作系统的进程最大可打开文件数
    worker_connections  1024;
    # 让worker进程一次性地接受监听队列里的所有请求
    multi_accept on;
}

http {
    # 缓存fastcgi生成的内容
    fastcgi_cache_key "$scheme$request_method$host$request_uri";
    fastcgi_cache_path /tmp/nginx levels=1:2 keys_zone=WORDPRESS:100m inactive=60m max_size=1g;
    fastcgi_cache_use_stale error timeout invalid_header http_500;
    fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 256k;
    fastcgi_intercept_errors on;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_names_hash_bucket_size 512;
    # 请求Header大小32k-128K
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    # 请求Body大小最大5m
    client_max_body_size 5m;

    # sendfile   on;
    tcp_nopush on;
    tcp_nodelay on;

    # KeepAlive 的超时时间
    keepalive_timeout 60;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /dev/null;

    # hide verson string
    server_tokens  off;

    gzip on;
    gzip_min_length  1k;
    gzip_buffers     4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 2;
    gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml;
    gzip_vary on;
    gzip_proxied   expired no-cache no-store private auth;
    gzip_disable   "MSIE [1-6]\.";

    proxy_temp_path /tmp/nginx/proxy_temp_dir;
    proxy_cache_path /tmp/nginx/proxy_cache_dir levels=1:2 keys_zone=cache_one:20m inactive=1d max_size=5g;
    client_body_buffer_size 512k;
    proxy_connect_timeout 60;
    proxy_read_timeout 60;
    proxy_send_timeout 60;
    proxy_buffer_size 32k;
    proxy_buffers 4 64k;
    proxy_busy_buffers_size 128k;
    proxy_temp_file_write_size 128k;
    proxy_next_upstream error timeout invalid_header http_500 http_503 http_404;
    proxy_cache cache_one;

    # 请求限制
    limit_conn_zone $binary_remote_addr zone=perip:10m;
    limit_conn_zone $server_name zone=perserver:10m;

    include /etc/nginx/conf.d/*.conf;
}
